### ISSUE TITLE
Could not build module 'TencentOpenApi'

### ISSUE THREAD

**Issue by gityoung** [lyeah-ios/QQOpenSDK#1]
Could not build module 'TencentOpenApi'

**Comment by zisulu** [comment]
> Could not build module 'TencentOpenApi'

你好，这里是自用的pod源，因为最新版本的 SDK 直接集成到OC项目中回报一些文件无法索引的错误，所以我删除了SDK中的两个文件，如果你需要使用pod，请使用官网下载的SDK自己制作

**Comment by zisulu** [comment]
具体删除了哪两个文件可以在我的commit记录里面看到

**Comment by zisulu** [comment]
> 具体删除了哪两个文件可以在我的commit记录里面看到

去掉这两个文件之后，编译是正常的，目前也没有发现其他问题，Could not build module 'TencentOpenApi' 应该是没有去掉这两个文件之前会报的错，我测试过了我这个不会有这个错误的

**Comment by mr-huangjian** [comment]
> Could not build module 'TencentOpenApi'

可以参考下我的解决办法：https://juejin.cn/post/6916432417506983949/
